#!/bin/bash

gcc -std=c89 $1 -o /dev/null > /dev/null 2>&1
C89=$?
gcc -std=c90 $1 -o /dev/null > /dev/null 2>&1
C90=$?
gcc -std=c99 $1 -o /dev/null > /dev/null 2>&1
C99=$?
gcc -std=c11 $1 -o /dev/null > /dev/null 2>&1
C11=$?
gcc -std=c17 $1 -o /dev/null > /dev/null 2>&1
C17=$?
gcc -std=c23 $1 -o /dev/null > /dev/null 2>&1
C23=$?
echo "Exit codes:"
echo "C89: $C89, C90: $C90, C99: $C99, C11: $C11, C17: $C17, C23: $C23"
