#!bin/bash


### Install adb
sudo dnf install android-tools
## Webkit
sudo dnf install webkit2gtk4.0
## Node & yarn
sudo dnf install nodejs yarnpkg gettext gettext-devel


### Install Cabextract for MS Fonts

wget https://www.cabextract.org.uk/cabextract-1.9.1.tar.gz
tar -xvf cabextract-1.9.1.tar.gz
cd cabextract-1.9.1
./configure --prefix=/usr/local && make
sudo make install
