#!/bin/sh

# Workspaces & Window Management
## Unset the keybinds for launching "favorite apps"
gsettings set org.gnome.shell.keybindings switch-to-application-1  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-2  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-3  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-4  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-5  "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-6  "[]"
## Set the keybinds for switching to workspace by number
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1  "['<Super>1']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2  "['<Super>2']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3  "['<Super>3']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4  "['<Super>4']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5  "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6  "['<Super>6']"
## Set the keybinds for moving window to workspace by number
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Shift><Super>1']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Shift><Super>2']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Shift><Super>3']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Shift><Super>4']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Shift><Super>5']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Shift><Super>6']"
## Set workspace names
gsettings set org.gnome.desktop.wm.preferences workspace-names "['💻', '📖', '🌐', '💬', '🎞️', '⌛']"

## Set window management keybinds
gsettings set org.gnome.desktop.wm.keybindings close "['<Alt>F4', '<Super>W']"
gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Super>c', '<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super>Tab']"

# App Launching Keybinds
gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Super>e']"

# Clipboard indicator settings
gsettings set org.gnome.shell.extensions.clipboard-indicator toggle-menu "['<Super>V']"
gsettings set org.gnome.shell.keybindings toggle-message-tray "['<Super>m']"
